name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BENCHMARK_BRANCHES: refs/heads/master refs/heads/develop
  CC: gcc-11
  CXX: g++-11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: "3.21.*"

      - name: Install Dependencies
        shell: bash
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; \
          sudo apt-get install gcc-11 g++-11 python3; \
          sudo apt-get update -qq;

      - name: Create build Folder
        working-directory: ${{github.workspace}}
        shell: bash
        run: mkdir -p build

      - name: Build
        working-directory: ${{github.workspace}}/build
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          CMAKE_FLAGS: >
            -S ${{github.workspace}}/test
            -B ${{github.workspace}}/build
        shell: bash
        run: |
          cmake $CMAKE_FLAGS; \
          cmake --build .

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        run: ctest
